language: java

jdk:
#  - openjdk11
  - oraclejdk13
before_cache:
  - 'rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock'
  - 'rm -fr $HOME/.gradle/caches/*/plugin-resolution/'
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - "chmod +x gradlew"

before_script:
  - "git config --global user.name 'GeunChang Ahn <rkaehdaos>'"
  - "git config --global user.email '13996827+rkaehdaos@users.noreply.github.com'"
  - "sed -i 's/__SLACK_TOKEN__/${__SLACK_TOKEN__}/' .travis.yml"
  - "sed -i 's/__COVERALLS_TOKEN__/${__COVERALLS_TOKEN__}/' .coveralls.yml"

script: "./gradlew clean build"

after_success:
  - "./gradlew jacocoTestReport coveralls"

notifications:
  slack: rkaehdaos:__SLACK_TOKEN__